### ISSUE TITLE
Start job for disk device hangs

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#221]
https://github.com/dracutdevs/dracut/issues/2648

@krisutofu 

Can you please post the output of `dracut -v` ? and also add `rd.debug` to the kernel command line and post the output.

I checked https://forum.garudalinux.org/t/since-the-linux-update-from-14th-of-april-or-maybe-one-or-two-days-before-linux-zen-will-hang-when-booting/36162 but it does not have information about your dracut configuration (e.g. which dracut modules are used)

https://wiki.archlinux.org/title/Dracut

**Comment by krisutofu** [comment]
Thank you for your initiative after the search engine led me to the wrong site.

Maybe I am getting the instructions wrong. In the Konsole terminal, `dracut -v` produces crazy output:
```
dracut: Executing: /usr/bin/dracut -v
dracut: Can't write to /boot/efi/dcd4639c7b1347ff9b746ff6b13bcba9/6.8.7-zen1-1-1zen: Directory /boot/efi/dcd4639c7b1347ff9b746ff6b13bcba9/6.8.7-zen1-1-zen does not exist or is not accesible.
```
(It does not exist btw.)

I retried it in the rescue mode console. It's the same (but probably to be expected because the console opens after the boot process finished.

As in [the linked Arch article on Dracut](https://wiki.archlinux.org/title/Dracut#Kernel_command_line_options) I tried
```
cat <<END | sudo tee /etc/dracut.conf.d/cmdine.conf
kernel_cmdline="rd.shell rd.debug"
END
```

I tried it with rd.shell and without. My command line shell script in GRUB is
```
load_video
set gfxpayload=keep
insmod gzip
insmod part_gpt
insmod btrfs
seearch --no-floppy --fs-uuid --set=root 11d26dd1-3904-490b-9e20-1b11c6731dc0
echo 'Loading Linux linux-zen ...'
linux /@/boot/vmlinuz-linux-zen root=UUID=11d26dd1-3904-490b-9e30-1b11c6731dc0 rw rootflags=subvol=@  quiet quiet rd.udev.log_priority=3 vt.global_cursor_default=0 resume=UUID=bbfad61d-c762-4f28-a49c-e041bde44e28 loglevel=3 ibt=off rd.debug
echo 'Loading initial ramdisk ...'
initrd /@/boot/intel-ucode.img /@/boot/initramfs-linux-zen.img
```
(typed down character by character from my keyboard)

I don't see a difference during the linux boot process, a lot of messages, all of them OK.

Adding `rd.debug` to the `linux` command in GRUB seems to show something but only for a fraction of a second. I cannot read it.

Okay, I am going to update Dracut now and try again.

I tried to comment out `initrd` to see output but it seems, the debug output is only shown when initrd starts.

When booting with the update, it's normal like before. For a very short time when `initrd` starts, over a screen height of text is running through and disappears immediately.

The only thing I can capture is this output:

```
ACPI BIOS Error (bug): Failure creating named object [\_SB.PC00.XHCI.RHUB.HS05._
ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20230628/psobjet-220
ACPI BIOS Error (bug): Failure creating named object [\_SB.PC00.XHCI.RHUBHS05._
ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20230628/psobject-220
ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - ^S
ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - ^S
ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - ^X
ACPI Error: AE_NOT_FOUND, While resolving a named reference package element - ^X
[ OK ] Stopped Virtual Console Setup.
          Stopped Virtual Console Setup...
         Starting Virtual Console Setup...
[ OK ] Started Slow Plymouth Boot Screen.
[ OK ] Started Forward Password Requests to Plymouth Directory Watch.
[ OK ] Reached target Path Units.
[ OK ] Finished Virtual Console Setup.
[ OK ] Found device Lexar SSD NNGA1 1TB garuda.
[ OK ] Reached target initrd Root Device.
[ *** ] A start job is running for /dev/disk/by-uuid/bbfa61d-c762-4f27-a4 …
```
(It showed for over 25 min when I rebooted with CTRL+ALT+Del. When I boot with the snapshot of Dracut 059-6, I do not have any such device UUID. The only partition, that I cannot get a UUID from is the original windows partition with unknown file system.)

It doesn't look like logging to the journalctl as I see almost 1h of nothing between shut down and the next boot (when I wrote the message above). There is no log file in `/run/initramfs/` and I don't know how I would set the dracut-logger variables at boot time.

Trying it from a live USB did not help either. It is likely a totally different version. When I entered `sudo dracut -v` it built an initramfs image. I do not really know how I could run the new Dracut program and I am running out of time on researching on what I need to do, typing and rebooting.

**Comment by krisutofu** [comment]
Okay, I am sorry for my incompetence. Looks like a simple change. It produces quite a lot of output.

Here it is:
[dracut_v.txt](https://github.com/dracut-ng/dracut-ng/files/15084505/dracut_v.txt)

**Comment by krisutofu** [comment]
Aha, hm.

I had the idea. I updated Dracut-ng with `sudo pacman -Sy dracut` without rebooting, so that I can actually use the command in a running system (nothing was changed in between).

It produces this ouptut:
[dracut-ng_v.txt](https://github.com/dracut-ng/dracut-ng/files/15093388/dracut-ng_v.txt)

Now I
```
diff <( sed -e 's/^dracut://g' -e 's/dracut module//g' -e 's/ [0-9]\{2\}:[0-9]\{2\}//g' -e 's/Mar\s\+[0-9]\+\|Apr\s\+[0-9]\+//g' dracut_v.txt ) <( sed -e 's/^dracut\[.\]://g' -e 's/Module//g' -e 's/ [0-9]\{2\}:[0-9]\{2\}//g' -e 's/Mar\s\+[0-9]\+\|Apr\s\+[0
-9]\+//g'  dracut-ng_v.txt ) > dracut_diff.txt
```
[dracut_diff.txt](https://github.com/dracut-ng/dracut-ng/files/15093718/dracut_diff.txt)

Summary

* new dracut says `If you need to use bluetooth, please include it explicitly.`
* old dracut skips some udev rules
* new dracut uses more files and additional module "resume"
* new dracut has bigger file sizes (exceptions below)

Files that appear only with new dracut:
```
659a658,659
>  drwxr-xr-x   1 root     root            0  usr/lib/modules/6.8.7-zen1-1-zen/kernel/drivers/dma/dw
>  -rw-r--r--   1 root     root         3564  usr/lib/modules/6.8.7-zen1-1-zen/kernel/drivers/dma/dw/dw_dmac.ko.zst
661a662
>  -rw-r--r--   1 root     root         8026  usr/lib/modules/6.8.7-zen1-1-zen/kernel/drivers/dma/idma64.ko.zst
906a908,909
>  -rw-r--r--   1 root     root         7446  usr/lib/modules/6.8.7-zen1-1-zen/kernel/drivers/mfd/intel-lpss-pci.ko.zst
>  -rw-r--r--   1 root     root         5374  usr/lib/modules/6.8.7-zen1-1-zen/kernel/drivers/mfd/intel-lpss.ko.zst
970a974,975
>  drwxr-xr-x   1 root     root            0  usr/lib/modules/6.8.7-zen1-1-zen/kernel/drivers/spi
>  -rw-r--r--   1 root     root        15486  usr/lib/modules/6.8.7-zen1-1-zen/kernel/drivers/spi/spi-pxa2xx-platform.ko.zst
…
1191a1197
>  -rwxr-xr-x   1 root     root        26976  usr/lib/systemd/system-generators/systemd-hibernate-resume-generator
1281a1288
>  lrwxrwxrwx   1 root     root           43  usr/lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup-dev-early.service -> ../systemd-tmpfiles-setup-dev-early.service
1292a1300
>  -rw-r--r--   1 root     root          666  usr/lib/systemd/system/systemd-hibernate-resume.service
1302a1310
>  -rw-r--r--   1 root     root          852  usr/lib/systemd/system/systemd-tmpfiles-setup-dev-early.service
1318a1327
>  -rwxr-xr-x   1 root     root        26936  usr/lib/systemd/systemd-hibernate-resume
```

These only mention Linux Zen which could be the reason why only Zen is not booting anymore with older snapshots. (Very creepy, snapshots which do not boot.)

Files only in old dracut
```
1300d1307
<  -rw-r--r--   1 root     root         1187  usr/lib/systemd/system/systemd-random-seed.service
```

**Comment by dalto8** [comment]
> This `btrfs-snapshot-overlay` dracut module is not maintained as part of the dracut project, so if the issue is with the `btrfs-snapshot-overlay`, than you need to report it there.
> 
> https://github.com/Antynea/grub-btrfs

In the case of Garuda, I believe this is coming from the Garuda repo, [here](https://gitlab.com/garuda-linux/pkgbuilds/-/tree/main/garuda-dracut-support).

**Comment by dalto8** [comment]
Are we sure this is related to dracut?

I did some quick testing to see what was going on here.  The actual failure is related to the error:
```t
overlay "No changes allowed in reconfigure."
```

It seems to happen only in kernel 6.8.  In my brief testing, the result was the same no matter what version of dracut I used.  I tried 059, 060 and 101.  It was just a quick test, so it is possible I missed something.

@krisutofu, I would be curious to know how the testing of dracut versions was done.  Is it possible that when you rolled back to an old version of dracut you also were bringing in an older kernel?

It seems to be related to this patch:
https://lore.kernel.org/all/20230620-fs-overlayfs-mount-api-remount-v1-1-6dfcb89088e3@kernel.org

**Comment by dalto8** [comment]
The garuda team fixed this issue.

https://gitlab.com/garuda-linux/pkgbuilds/-/commit/26d7f8496c242265b6902ee9188f134194cd0c0b

**Comment by JustTNE** [comment]
To me, it does seem like this is a kernel bug still, given that mounting a single subvolume that prefers to be RO (no explicit RO) should not cause ALL submodules mounted from then on to be considered RO. That would imply the order of mounts matters, which is rather silly, but here we are.

**Comment by krisutofu** [comment]
> Are we sure this is related to dracut?
> 
> I did some quick testing to see what was going on here. The actual failure is related to the error:
> 
> ```perl
> overlay "No changes allowed in reconfigure."
> ```
> 
> It seems to happen only in kernel 6.8. In my brief testing, the result was the same no matter what version of dracut I used. I tried 059, 060 and 101. It was just a quick test, so it is possible I missed something.
> 
> @krisutofu, I would be curious to know how the testing of dracut versions was done. Is it possible that when you rolled back to an old version of dracut you also were bringing in an older kernel?
> 
> It seems to be related to this patch: https://lore.kernel.org/all/20230620-fs-overlayfs-mount-api-remount-v1-1-6dfcb89088e3@kernel.org

Thank you for your investigation. Well, I initially suspected the Kernel but when I isolated the problem it was just the Dracut update to 101-1 which caused my issues. And yes, any Linux-Zen snapshots wouldn't boot, that's right, only the most recent version booted with Linux Zen before it happened that no recent Linux image booted anymore. I have been able to update everything, including the Kernel, and it would boot without problems. Until my last update (before the fix was released by the Garuda-Team) I always updated everything except for Dracut and it worked.

I did not notice read-only mounting issues. Rather, it could not find the disk device at all.

**Comment by krisutofu** [comment]
How does the start job gets the disk device UUIDs that it wants to start?

I remember that I once moved the swap partition with KDE Partition Manager and I had to fix it in the `/etc/fstab`. Now, my `fstab` and `lsblk -f` doesn't show the UUID that the start job is unsuccessfully running for but could it be, there is somehow somewhere a remnant of the old swap partition?
