### ISSUE TITLE
netroot=... fails with systemd-networkd

### ISSUE THREAD

**Issue by LaszloGombos** [dracut-ng/dracut-ng#251]
See this PR to reproduce - https://github.com/dracut-ng/dracut-ng/pull/238

**Comment by BtbN** [comment]
I've ran into this as well, and the core issue seems to be that the systemd-networkd network module has no provisions at all to call the netroot.sh script provided by the net-lib module, so no netroot setup and mounting is ever actually performed.

**Comment by BtbN** [comment]
No, likely has been the case since forever. There is absolutely no logic in the systemd-networkd module that'd ever call any kind of netroot script, and as far as I can tell, this has never existed either.

There is two core issues with the networkd module right now:

It does not call the netroot script whenever an interface goes online, so all the netroot modules are defunct with it.
It does also not parse the ip= commandline parameters. In fact, by default it does not even bring the network up unless in hostonly mode and a fitting .network config file happens to have been copied.

I implemented a crude workaround to this in my custom netroot module.
It adds a script to the initqueue, which calls "$systemdutildir"/systemd-networkd-wait-online with a short timeout, and when it succeeds, calls the netroot script.
Something similar but more involved, alongside with a ip=-argument-to-networkd-config generate, needs to be developed for it to be a generic replacement for the others.

This is slowly getting more pressing, since the days of dhclient, and thus network-legacy, are counted, and neither connman nor NM are suitable in our setup.

**Comment by LaszloGombos** [comment]
NFS also seems to fail with systemd-networkd

https://bugzilla.redhat.com/show_bug.cgi?id=1989119

Other networkd issues (listing them here as it might better characterize whats missing form networkd):
 - https://github.com/dracutdevs/dracut/issues/1822
 - https://github.com/dracutdevs/dracut/issues/1386

**Comment by BtbN** [comment]
As I said, every single netroot will fail with networkd, since it has no provisions to call the netroot.sh script.

**Comment by LaszloGombos** [comment]
CC @pothos for visibility and feedback
